# Site settings
title: Gnomesorting
email: thammovo@eng.utah.edu
description: "Just a site where i post my old school work projects and other projects I am working on at the moment"
baseurl: ""
url: "willthamzizzle.github.io"

# Build settings
markdown: kramdown
permalink: pretty
