# Site settings
title: Gnomesorting
footerTitle: William Thammavong
email: thammavo@eng.utah.edu
description: "A software guys musing on life"
baseurl: ""
url: "willthamzizzle.github.io"

# usernames for various social media stuff
twittername: willintowill
githubname: willthamzizzle

# Build settings
markdown: kramdown
permalink: pretty
